kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "gogs.fullname" . }}-config
  labels:
    app: {{ include "gogs.fullname" . }}
data:
  app.ini: |
    RUN_MODE = prod
    RUN_USER = gogs

    [database]
    DB_TYPE  = postgres
    HOST     = {{ include "postgresql.hostname" . }}:{{ include "postgresql.port" . }}
    NAME     = {{ include "postgresql.database" . | quote }}
    USER     = {{ include "postgresql.username" . | quote }}
    PASSWORD = {{ include "postgresql.password" . | quote }}

    [log]
    ROOT_PATH = /var/log/gogs

    [repository]
    ROOT = /opt/gogs/data/repositories

    [server]
    ROOT_URL=http://{{ required "A valid .Values.hostname entry required!" .Values.hostname }}
    SSH_DOMAIN={{ required "A valid .Values.hostname entry required!" .Values.hostname }}

    [security]
    INSTALL_LOCK = {{ include "gogs.installLock" . }}

    [service]
    ENABLE_CAPTCHA = false

    [webhook]
    SKIP_TLS_VERIFY = {{ include "gogs.skipTlsVerify" . }}
