apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gogs.fullname" . }}-data
  labels:
    {{- include "gogs.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ include "gogs.volume.capacity" . }}
