apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "gogs.fullname" . }}
  labels:
    {{- include "gogs.labels" . | nindent 4 }}
spec:
  host: {{ .Values.hostname }}
  port:
    targetPort: {{ .Values.service.port }}-http
  to:
    kind: Service
    name: {{ include "gogs.fullname" . }}
    weight: 100
  wildcardPolicy: None
